#!/bin/sh

# Migrate existing nginx configs to projects.conf
# Parses existing nginx/conf.d/*.conf files and creates projects.conf

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$PROJECT_ROOT/projects.conf"
NGINX_CONF_D="$PROJECT_ROOT/nginx/conf.d"
CONFIG_EXAMPLE="$PROJECT_ROOT/projects.conf.example"

# Check if yq is installed
if ! command -v yq >/dev/null 2>&1; then
  echo "Error: yq is not installed. Install it with: brew install yq"
  exit 1
fi

# Check if projects.conf already exists
if [ -f "$CONFIG_FILE" ]; then
  echo "Warning: projects.conf already exists!"
  printf "Do you want to overwrite it? (y/n): "
  read -r answer
  if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
    echo "Migration cancelled"
    exit 0
  fi
  # Backup existing config
  cp "$CONFIG_FILE" "$CONFIG_FILE.backup.$(date +%Y%m%d_%H%M%S)"
  echo "Backed up existing projects.conf"
fi

# Create projects.conf from example
if [ -f "$CONFIG_EXAMPLE" ]; then
  cp "$CONFIG_EXAMPLE" "$CONFIG_FILE"
  # Remove example projects
  yq eval 'del(.myapp, ."another-project")' -i "$CONFIG_FILE" 2>/dev/null || true
else
  # Create empty config
  echo "# DockMaster Projects Configuration" > "$CONFIG_FILE"
  echo "# Migrated from existing nginx configs" >> "$CONFIG_FILE"
  echo "" >> "$CONFIG_FILE"
fi

# Load .env variables
if [ -f "$PROJECT_ROOT/.env" ]; then
  export $(grep -v '^#' "$PROJECT_ROOT/.env" | xargs)
fi

DNSMASQ_DOMAIN="${DNSMASQ_DOMAIN:-.test}"

echo "Migrating nginx configs to projects.conf..."
echo ""

# Process each nginx config file
for conf_file in "$NGINX_CONF_D"/*.conf; do
  if [ ! -f "$conf_file" ]; then
    continue
  fi
  
  # Skip generated files and mailpit
  if grep -q "# Generated by generate-nginx-configs.sh" "$conf_file" 2>/dev/null; then
    continue
  fi
  
  filename=$(basename "$conf_file" .conf)
  
  # Skip mailpit
  if [ "$filename" = "mailpit" ]; then
    continue
  fi
  
  echo "Processing: $filename"
  
  # Extract domain from server_name
  domain=$(grep -E "^\s*server_name\s+" "$conf_file" | head -1 | sed 's/.*server_name\s\+\([^;]*\);.*/\1/' | tr -d ' ' || echo "")
  
  if [ -z "$domain" ]; then
    echo "  Warning: Could not extract domain, skipping"
    continue
  fi
  
  # Determine project type by checking proxy_pass
  proxy_pass_line=$(grep -E "proxy_pass\s+" "$conf_file" | head -1 || echo "")
  fastcgi_pass_line=$(grep -E "fastcgi_pass\s+" "$conf_file" | head -1 || echo "")
  
  project_type="proxy"
  http_port=""
  https_port=""
  ssl_enabled="false"
  target_container=""
  proxy_type="80"
  fpm_port="9000"
  
  # Check if SSL is enabled
  if grep -q "listen 443 ssl" "$conf_file"; then
    ssl_enabled="true"
  fi
  
  # Check if it's a proxy (host.docker.internal) or site (container name)
  if echo "$proxy_pass_line" | grep -q "host.docker.internal"; then
    project_type="proxy"
    
    # Extract port from proxy_pass
    if echo "$proxy_pass_line" | grep -q "http://host.docker.internal:"; then
      http_port=$(echo "$proxy_pass_line" | sed 's/.*http:\/\/host\.docker\.internal:\([0-9]*\).*/\1/' || echo "")
    elif echo "$proxy_pass_line" | grep -q "https://host.docker.internal:"; then
      https_port=$(echo "$proxy_pass_line" | sed 's/.*https:\/\/host\.docker\.internal:\([0-9]*\).*/\1/' || echo "")
    fi
    
    # Check for HTTP port
    if grep -q "listen 80" "$conf_file" && ! grep -q "return 301" "$conf_file"; then
      if [ -z "$http_port" ]; then
        # Try to extract from proxy_pass in HTTP block
        http_port=$(grep -A 10 "listen 80" "$conf_file" | grep "proxy_pass" | sed 's/.*:\([0-9]*\).*/\1/' | head -1 || echo "")
      fi
    fi
  else
    project_type="site"
    
    # Extract container name
    if [ -n "$fastcgi_pass_line" ]; then
      proxy_type="fpm"
      target_container=$(echo "$fastcgi_pass_line" | sed 's/.*\$backend = "\([^:]*\):.*/\1/' | sed 's/.*fastcgi_pass[[:space:]]*\$backend[[:space:]]*\([^:;]*\):.*/\1/' || echo "")
      fpm_port=$(echo "$fastcgi_pass_line" | sed 's/.*:\([0-9]*\).*/\1/' | head -1 || echo "9000")
    elif [ -n "$proxy_pass_line" ]; then
      target_container=$(echo "$proxy_pass_line" | sed 's/.*\$backend = "\([^"]*\)".*/\1/' | sed 's/.*proxy_pass[[:space:]]*\(https\?\):\/\/\$backend.*/\1/' || echo "")
      
      if echo "$proxy_pass_line" | grep -q "https://"; then
        proxy_type="ssl"
      else
        proxy_type="80"
      fi
    fi
  fi
  
  # Add project to YAML using yq
  yq eval ".$filename.type = \"$project_type\"" -i "$CONFIG_FILE"
  yq eval ".$filename.domain = \"$domain\"" -i "$CONFIG_FILE"
  yq eval ".$filename.enabled = true" -i "$CONFIG_FILE"
  yq eval ".$filename.ssl = $([ "$ssl_enabled" = "true" ] && echo "true" || echo "false")" -i "$CONFIG_FILE"
  
  if [ "$project_type" = "proxy" ]; then
    if [ -n "$http_port" ]; then
      yq eval ".$filename.http.port = $http_port" -i "$CONFIG_FILE"
      yq eval ".$filename.http.enabled = true" -i "$CONFIG_FILE"
    else
      yq eval ".$filename.http.port = null" -i "$CONFIG_FILE"
      yq eval ".$filename.http.enabled = false" -i "$CONFIG_FILE"
    fi
    
    if [ -n "$https_port" ]; then
      yq eval ".$filename.https.port = $https_port" -i "$CONFIG_FILE"
      yq eval ".$filename.https.enabled = true" -i "$CONFIG_FILE"
    else
      yq eval ".$filename.https.port = null" -i "$CONFIG_FILE"
      yq eval ".$filename.https.enabled = false" -i "$CONFIG_FILE"
    fi
  else
    if [ -n "$target_container" ]; then
      yq eval ".$filename.target.container = \"$target_container\"" -i "$CONFIG_FILE"
      yq eval ".$filename.target.proxy_type = \"$proxy_type\"" -i "$CONFIG_FILE"
      
      if [ "$proxy_type" = "fpm" ]; then
        yq eval ".$filename.target.fpm.container = \"$target_container\"" -i "$CONFIG_FILE"
        yq eval ".$filename.target.fpm.port = ${fpm_port:-9000}" -i "$CONFIG_FILE"
        yq eval ".$filename.target.fpm.enabled = true" -i "$CONFIG_FILE"
      fi
    fi
  fi
  
  # MySQL proxying - we can't detect this from nginx configs, so leave it disabled
  yq eval ".$filename.mysql.enabled = false" -i "$CONFIG_FILE"
  
  # Docker compose - not available from nginx configs
  yq eval ".$filename.docker.compose = null" -i "$CONFIG_FILE"
  yq eval ".$filename.docker.override = null" -i "$CONFIG_FILE"
  
  echo "  Added: $filename ($project_type) - $domain"
done

echo ""
echo "Migration completed!"
echo "Please review projects.conf and add any missing information (MySQL ports, Docker compose paths, etc.)"
echo "Then run: ./scripts/project-manager.sh regenerate"
